### ISSUE TITLE
Error installing chrome plugin

### ISSUE THREAD

**Issue by aberezin** [labsansis/garmin-workout-downloader#13]
MacOS 13.6.1 (22G313)
Chrome is up to date:  Version 119.0.6045.159 (Official Build) (x86_64)

See screenshot
[<img width="1521" alt="image" src="https://github.com/labsansis/garmin-workout-downloader/assets/1704031/5a7bc0e2-f0ee-4105-a728-47a0e84b4479">](https://app.screencast.com/8svWLjnuzdNZS)

**Comment by labsansis** [comment]
Thanks for reporting this!

If the SVG file is actually the issue, I'm a little surprised that it wasn't picked up during development & testing. Will look into this in the next couple of days.

**Comment by labsansis** [comment]
Ok so this was not caught during development because Chrome seems to support SVGs just fine when you load an extension from source, but not when you install an extension from the Chrome Web Store.

I have now pushed a fix to the Chrome Web Store which is going through a review. I don't know how long this review will take (according to them could be weeks), and I don't have any way of testing that the issue has actually been resolved until the fix is published on the Web Store.

With the inconsistent extension behavior, the length of the review process and the fact that this review doesn't even check that the extension can be installed, I have to say this has been pretty poor experience on the Chrome side...

**Comment by markbulk** [comment]
It's already updated on the Chrome store.

I can verify that it will pull down a json file when run in an open Garmin Connect window.

Thanks!!

**Comment by labsansis** [comment]
Nice, closing this as resolved.
